# vim:ft=ansible:
- name: create machine
  hosts: localhost
  gather_facts: no
  tags: create

  tasks:
  - docker_machine:
      name: test-machine
      state: present
      driver: digitalocean
      digitalocean_access_token: "{{ token }}"
      digitalocean_region: ams3

- name: deploy machine
  hosts: test-machine
  connection: docker_machine
  gather_facts: no
  tags: deploy

  tasks:
  - docker:
      name: nginx
      image: nginx
      state: started
      use_tls: encrypt
      ports:
        - "80:80"

