# vim:ft=ansible:

- name: create machine
  hosts: localhost
  connection: local
  gather_facts: no
  tags: create

  tasks:
  - shell: >
      docker-machine create
      --driver digitalocean
      --digitalocean-access-token {{ token }}
      --digitalocean-region ams3
      test-machine
    changed_when: false

- name: deploy machine
  hosts: test-machine
  connection: docker_machine
  gather_facts: no
  tags: deploy

  tasks:
  - docker:
      name: nginx
      image: nginx
      state: started
      use_tls: encrypt
      ports:
        - "80:8080"

